#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'bahn.guru:~/bahn.guru/'

ssh bahn.guru "\
cd ~/bahn.guru
npm i
npm update
forever stop bahn.guru
npm run build
export NODE_ENV=production
forever start -a --uid bahn.guru index.js"