#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude '*.log' \
	--exclude node_modules \
	. 'enceladus:~/bahn.guru/'

ssh enceladus "\
cd ~/bahn.guru
npm i
npm update
forever stop bahn.guru
npm run build
forever start -a --uid bahn.guru index.js"
