#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude '*.log' \
	--exclude 'bundle-*.js' \
	--exclude node_modules \
	. 'europa:~/bahn.guru/'

ssh europa "\
cd ~/bahn.guru
npm i
npm update
forever-service delete bahn-calendar
export NODE_ENV=bahn
npm run build
forever-service install bahn-calendar -e 'NODE_ENV=bahn ENV=bahn' --start -s index.js"
