#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude '*.log' \
	--exclude 'assets/scripts/bundle/*.js' \
	--exclude node_modules \
	. 'europa:~/bahn.guru/'

ssh europa "\
cd ~/bahn.guru
npm i
npm update
forever-service delete bahn-calendar
export NODE_ENV=production ENV=production API=bahn PORT=3009
npm run build
forever-service install bahn-calendar -e 'NODE_ENV=production ENV=production API=bahn PORT=3009' --start -s index.js"
