#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude '*.log' \
	--exclude 'bundle-*.js' \
	--exclude node_modules \
	. 'europa:~/bahn.guru/'

ssh europa "\
cd ~/bahn.guru
npm i
npm update
forever-service delete bus-calendar
export NODE_ENV=production ENV=production API=bus PORT=3039
npm run build
forever-service install bus-calendar -e 'NODE_ENV=production ENV=production API=bus PORT=3039' --start -s index.js"
