#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude '*.log' \
	--exclude node_modules \
	. 'europa:~/bahn.guru/'

ssh europa "\
cd ~/bahn.guru
npm i
npm update
forever-service delete bus-calendar
export NODE_ENV=bus
npm run build
forever-service install bus-calendar -e 'NODE_ENV=bus ENV=bus' --start -s index.js"
